---
services:
  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    container_name: minio
    restart: always
    command:
      - server
      - /data
      - --console-address
      - :443
      - --address
      - :9000
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - minio:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.minio.rule: Host(`mc.docker.localhost`)
      traefik.http.services.minio.loadbalancer.server.port: 443
      # traefik.http.routers.minio.entryPoints: https
      # traefik.http.middlewares.minio-https-redirect.redirectscheme.scheme: https



  # nginx:
  #   image: nginxinc/nginx-s3-gateway:latest-njs-oss
  #   container_name: nginx
  #   restart: always
  #   expose:
  #     - 80
  #   environment:
  #     AWS_SECRET_ACCESS_KEY: CHANGEME123
  #     AWS_ACCESS_KEY_ID: ROOTNAME
  #     S3_REGION: us-east-1
  #     AWS_SIGS_VERSION: '4'
  #     S3_SERVER: minio
  #     S3_SERVER_PORT: '9000'
  #     S3_SERVER_PROTO: http
  #     S3_BUCKET_NAME: reports
  #     ALLOW_DIRECTORY_LIST: 'true'
  #     S3_STYLE: path
  #     PROVIDE_INDEX_PAGE: 'true'
  #     PROXY_CACHE_VALID_OK: 0s
  #     PROXY_CACHE_INACTIVE: 0s
  #     PROXY_CACHE_VALID_NOTFOUND: 0s
  #     PROXY_CACHE_VALID_FORBIDDEN: 0s
  #   labels:
  #     - traefik.http.routers.nginx.rule=Host(`www.docker.localhost`)
  #     - traefik.http.routers.nginx.entryPoints=https
  #     - traefik.http.routers.nginx.tls=true
  #     - traefik.http.routers.nginx.middlewares=auth@file

  traefik:
    image: traefik:v3.1
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: "Host(`traefik.docker.localhost`)"
      traefik.http.routers.traefik.middlewares: auth@file
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
    volumes:
      - ${PWD}/configs/traefik:/etc/traefik:ro
      - ${PWD}/tmp/tls:/etc/tls:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443

  authelia:
    image: authelia/authelia:4.38
    user: ${UID}:${GID}
    labels:
      traefik.enable: "true"
      traefik.http.routers.authelia.rule: "Host(`auth.docker.localhost`)"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"
    volumes:
      - ${PWD}/tmp/tls:/etc/tls:ro
      - ${PWD}/tmp/authelia/log:/var/log/authelia:rw
      - ${PWD}/tmp/authelia/secrets:/storage/secrets:ro
      - ${PWD}/tmp/authelia/db:/storage/db:rw
      - ${PWD}/configs/authelia:/config:ro

    environment:
      - PUID=${UID}
      - PGID=${GID}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/storage/secrets/AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/storage/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE

volumes:
  minio: {}
