---
version: "3"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-05T22-17-24Z
    container_name: minio
    restart: always
    command:
      - server
      - /data
      - --console-address
      - :9080
      - --address
      - :9000
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - minio:/data
    labels:
      - traefik.http.routers.minio.rule=Host(`minio.docker.localhost`)
      - traefik.http.services.minio.loadbalancer.server.port=9080
      - traefik.http.routers.minio.entryPoints=https
      - traefik.http.routers.minio.tls=true

  nginx:
    image: nginxinc/nginx-s3-gateway:latest-njs-oss
    container_name: nginx
    restart: always
    expose:
      - 80
    environment:
      AWS_SECRET_ACCESS_KEY: CHANGEME123
      AWS_ACCESS_KEY_ID: ROOTNAME
      S3_REGION: us-east-1
      AWS_SIGS_VERSION: '4'
      S3_SERVER: minio
      S3_SERVER_PORT: '9000'
      S3_SERVER_PROTO: http
      S3_BUCKET_NAME: reports
      ALLOW_DIRECTORY_LIST: 'true'
      S3_STYLE: path
      PROVIDE_INDEX_PAGE: 'true'
      PROXY_CACHE_VALID_OK: 0s
      PROXY_CACHE_INACTIVE: 0s
      PROXY_CACHE_VALID_NOTFOUND: 0s
      PROXY_CACHE_VALID_FORBIDDEN: 0s
    labels:
      - traefik.http.routers.nginx.rule=Host(`www.docker.localhost`)
      - traefik.http.routers.nginx.entryPoints=https
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.middlewares=auth@file

  traefik:
    image: traefik:v2.11
    container_name: traefik
    environment:
      traefik_hostname: docker.localhost
    volumes:
      - ${PWD}/configs/traefik:/etc/traefik:ro
      - ${PWD}/configs/tls:/etc/tls:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080

  authelia:
    container_name: authelia
    image: authelia/authelia:4
    restart: always
    expose:
      - 9091
    volumes:
      - ${PWD}/configs/authelia/config:/config:ro
      - ${PWD}/configs/authelia/storage:/storage:rw
      - ${PWD}/configs/tls:/etc/tls:ro
      - ${PWD}/configs/authelia/secrets:/run/secrets:ro
    environment:
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/SESSION_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/STORAGE_ENCRYPTION_KEY
    labels:
      - traefik.http.routers.authelia.rule=Host(`auth.docker.localhost`)
      - traefik.http.routers.authelia.entryPoints=https
      - traefik.http.routers.authelia.tls=true

volumes:
  minio: {}
