---
services:
  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    container_name: minio
    restart: always
    command:
      - server
      - /data
      - --console-address
      - :9443
      - --address
      - :9000
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - minio:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.mc.rule: Host(`mc.docker.localhost`)
      traefik.http.routers.mc.service: mc
      traefik.http.services.mc.loadbalancer.server.port: 9443
      traefik.http.routers.minio.rule: Host(`minio.docker.localhost`)
      traefik.http.routers.minio.service: minio
      traefik.http.services.minio.loadbalancer.server.port: 9000
      traefik.http.routers.minio.middlewares: auth@file,sigv4@file

  traefik:
    image: traefik:v3.1
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.rule: "Host(`traefik.docker.localhost`)"
      # traefik.http.routers.traefik.middlewares: auth@file
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
    volumes:
      - ${PWD}/configs/traefik:/etc/traefik:ro
      - ${PWD}/tmp/tls:/etc/tls:ro
      - ${PWD}/pkg/sigv4middleware:/plugins-local/src/github.com/samerbahri98/sigv4middleware
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443

  authelia:
    image: authelia/authelia:4.38
    user: ${UID}:${GID}
    labels:
      traefik.enable: "true"
      traefik.http.routers.authelia.rule: "Host(`auth.docker.localhost`)"
      traefik.http.services.authelia.loadbalancer.server.port: "9091"
    volumes:
      - ${PWD}/tmp/tls:/etc/tls:ro
      - ${PWD}/tmp/authelia/log:/var/log/authelia:rw
      - ${PWD}/tmp/authelia/secrets:/storage/secrets:ro
      - ${PWD}/tmp/authelia/db:/storage/db:rw
      - ${PWD}/configs/authelia:/config:ro

    environment:
      - PUID=${UID}
      - PGID=${GID}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/storage/secrets/AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/storage/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE

volumes:
  minio: {}
