---
http:
  middlewares:
    sigv4:
      plugin:
        sigv4middleware:
          accessKey: ROOTNAME
          secretKey: CHANGEME123
          service: s3
          endpoint: minio.docker.localhost
          region: us-east-1
    auth:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.docker.localhost%2F
        tls:
          ca: /etc/tls/cert.pem
          cert: /etc/tls/cert.pem
          key: /etc/tls/cert.key
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/tls/cert.pem
        keyFile: /etc/tls/cert.key

