---
api:
  dashboard: true
  debug: true

providers:
  docker:
    defaultRule: Host(`{{ .Name }}.docker.localhost`)
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        domains:
          - main: docker.localhost
            sans:
              - '*.docker.localhost'
