---
providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

api:
  insecure: true

log:
  level: DEBUG
